name: Run Python Code with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Run Python script
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: patient
          POSTGRES_PASSWORD: patient
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          python create-postgre-db-objects.py


        working-directory: .